name: BackPack
version: ${project.version}
main: com.ainar.backpack.BackPackPlugin
api-version: 1.16
softdepend: [Vault, HeadDatabase]
commands:
  mochila:
    description: Abre tu mochila progresiva o adminístrala.
    aliases: [backpack]
    permission: backpack.use
    usage: /mochila [admin/give]
permissions:
  backpack.use:
    description: Permite usar la mochila personal.
    default: true
  backpack.admin:
    description: Permite administrar la mochila de otros jugadores.
    default: op
